image: jamesdbloom/docker-java7-maven

package:
    script: "mvn clean package"

site:
    script: "mvn -gs /home/gitlab_ci_multi_runner/data/settings.xml clean site-deploy"

ll:
    script: "pwd && ls -la && cd /home && ls -la && cd /home/gitlab_ci_multi_runner/data && ls -la"
