image: jamesdbloom/docker-java7-maven

before_script:
    - chmod u+x release.sh
    - . ./release.sh

release:
    script:
        - mvn -gs /home/m2/settings.xml -DdevelopmentVersion=$DEV_VERSION -DreleaseVersion=$RELEASE_VERSION -DpreparationGoals="clean install" -DscmCommentPrefix="[maven-release-plugin] [ci skip] " -P t3-archive release:clean release:prepare release:perform
        - "curl -X POST -F token=$REBUILD_TOKEN -F ref=master https://git.teecu.be/api/v3/projects/$CI_PROJECT_ID/trigger/builds"
        - "curl -X POST -F token=$REBUILD_TOKEN -F ref=t3/$RELEASE_VERSION https://git.teecu.be/api/v3/projects/$CI_PROJECT_ID/trigger/builds"
    only:
        - release
