image: jamesdbloom/docker-java7-maven

before_script:
    - alias maven="mvn -gs /home/gitlab_ci_multi_runner/data/m2/settings.xml"

test:
    script: "mvn -gs /home/gitlab_ci_multi_runner/data/m2/settings.xml clean install"
    except:
        - releas.*

site:
    script: "mvn -gs /home/gitlab_ci_multi_runner/data/m2/settings.xml clean site-deploy -P t3-snapshot"
    except:
        - releas.*

release:
    stage: build
    script:
        - mvn -gs /home/gitlab_ci_multi_runner/data/m2/settings.xml -P t3-release release:clean release:prepare release:perform
    only:
        - release
    except:
        - branches
        - tags
